version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/flask-app

permissions:
  - object: /home/ubuntu/flask-app
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
